import { Roadmap, StudentProgress } from '@/types/sdg';

export const MergeManager = {
  /**
   * Concatenates completed module code into a single executable block.
   */
  mergeImpactArtifact(roadmap: Roadmap, progress: StudentProgress[]): string {
    const header = `"""\nSDG Impact Artifact: ${roadmap.primarySDG.name}\nGenerated by Sustain-Ability AI\n"""\n\n`;
    
    const mergedCode = roadmap.modules.map(mod => {
      const p = progress.find(item => item.moduleId === mod.id);
      if (p && p.status === 'COMPLETED') {
        return `# --- ${mod.title} ---\n${p.savedCode || ''}\n`;
      }
      return `# --- ${mod.title} --- (Incomplete)\n`;
    }).join('\n');

    const footer = `\n\n# End of Impact Logic\nprint("Impact Manifested Success")`;
    
    return header + mergedCode + footer;
  }
};
